//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoAuto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int comment_id { get; set; }
        public int ticket_id { get; set; }
        public int author_id { get; set; }
        public string comment_text { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<bool> is_internal { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
