//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoAuto2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistory
    {
        public int history_id { get; set; }
        public int ticket_id { get; set; }
        public int changed_by { get; set; }
        public string change_type { get; set; }
        public string old_value { get; set; }
        public string new_value { get; set; }
        public Nullable<System.DateTime> change_date { get; set; }
        public string comment { get; set; }
        public string EmployUpdate { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
